[tool.poetry]
name = "fastweb1"
version = "0.1.0"
description = ""
authors = ["khkwon01 <khkwon01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
